General:
    url: ''
    name: 'Stockpotatoes'
    description: ''
    studentPass: 'Yes'
color:
    theme:
        main: '#0080ff'
        second: '#ff8000'
        hover: '#01a6fe'
        focus: '#0000ff'
navBar:
    espaceEleve: 0,Login,login_eleve.php
espaceEleve:
    color: ""
    accesThemes:
        sup: 'Yes'
        inf: 'Yes'
        supDate: 'No'
        infDate: 'No'